### ISSUE TITLE
Cannot load such file -- options (LoadError)

### ISSUE THREAD

**Issue by huyvohcmc** [filestack/filestack-ruby#32]
**Version**:
```
Ruby: 2.3.3
Rails: 4.2
Filestack: 2.3.0
```

**Gemfile**:
```ruby
gem 'filestack', '2.3.0'
```

**rails c**:
```bash
/Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require': cannot load such file -- options (LoadError)
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/progress_bar-0.3.1/lib/progress_bar.rb:2:in `<main>'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/filestack-2.3.0/lib/filestack/utils/multipart_upload_utils.rb:7:in `<main>'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/filestack-2.3.0/lib/filestack/mixins/filestack_common.rb:3:in `<main>'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/filestack-2.3.0/lib/filestack/models/filelink.rb:5:in `<main>'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/filestack-2.3.0/lib/filestack.rb:1:in `<main>'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `each'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `block in require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `each'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.3/lib/bundler.rb:114:in `require'
        from /Users/huyvo/Projects/employment-hero/config/application.rb:6:in `<top (required)>'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
        from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/huyvo/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/huyvo/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

Both filestack 2.3.0 and 2.4.0 results with the same error.

**Comment by gabifiolek** [comment]
@huyvohcmc do you provide options for upload?
https://www.rubydoc.info/gems/filestack/2.4.0/FilestackClient#upload-instance_method

**Comment by huyvohcmc** [comment]
@gabifiolek I didn't even write any code related to Filestack...

**Comment by gabifiolek** [comment]
@huyvohcmc OK. So could you please list gems  - `gem list`? , it looks like some issue with bootsnap-1.1.8

**Comment by huyvohcmc** [comment]
@gabifiolek
```bash
aasm (5.0.0, 4.12.3, 4.5.0)
abn (2.1.1, 2.0.0)
actioncable (5.0.6, 5.0.2)
actionmailer (5.0.6, 5.0.2, 4.2.9)
actionpack (5.0.6, 5.0.2, 4.2.9)
actionview (5.0.6, 5.0.2, 4.2.9)
active_model-errors_details (1.3.1)
active_model_serializers (0.10.7, 0.10.4)
active_record_union (1.3.0, 1.1.0)
activejob (5.0.6, 5.0.2, 4.2.9)
activemodel (5.0.6, 5.0.2, 4.2.9)
activerecord (5.0.6, 5.0.2, 4.2.9)
activesupport (5.0.6, 5.0.2, 4.2.9, 4.2.8)
acts-as-taggable-on (5.0.0, 3.5.0)
acts_as_commentable_with_threading (2.0.1, 2.0.0)
addressable (2.5.2, 2.4.0)
afm (0.2.2)
airbrake (4.1.0)
amq-protocol (2.3.0, 2.2.0, 2.1.0)
ar-octopus (0.9.2)
archive-zip (0.11.0, 0.7.0)
arel (7.1.4, 6.0.4)
Ascii85 (1.0.3, 1.0.2)
ast (2.4.0, 2.3.0)
atomos (0.1.3, 0.1.2)
attr_encryptor (2.0.0)
audit_hero (0.3.4, 0.3.2)
awesome_nested_set (3.1.4, 3.0.2)
awesome_print (1.8.0, 1.7.0, 1.6.1)
aws-eventstream (1.0.1)
aws-partitions (1.102.0)
aws-sdk (2.0.48)
aws-sdk-core (3.26.0, 2.0.48)
aws-sdk-kms (1.8.0)
aws-sdk-resources (2.0.48)
aws-sdk-s3 (1.18.0)
aws-sdk-v1 (1.67.0, 1.64.0)
aws-sigv4 (1.0.3)
axiom-types (0.1.1)
babosa (1.0.2)
backports (3.11.4)
bacon (1.2.0)
badge (0.9.1)
bcrypt (3.1.12, 3.1.11)
better_errors (2.5.0, 2.1.1)
bigdecimal (default: 1.2.8)
binding_of_caller (0.8.0, 0.7.2)
bitmask_attributes (1.0.0)
bootsnap (1.3.1, 1.1.8)
bootstrap-kaminari-views (0.0.5)
braintree (2.90.0, 2.45.0)
brakeman (4.3.1)
browser (2.5.3, 0.8.0)
builder (3.2.3)
bump (0.6.0)
bundler (1.16.3)
bundler-audit (0.6.0)
bundler-unload (1.0.2)
bunny (2.9.2, 2.8.0, 2.6.3)
byebug (10.0.2, 9.1.0, 9.0.6)
capybara (2.7.1)
carrierwave (1.2.3, 0.10.0)
carrierwave-aws (1.3.0, 0.6.0)
carrot-top (0.0.7)
case_transform (0.2)
celluloid (0.17.3, 0.17.2)
celluloid-essentials (0.20.5)
celluloid-extras (0.20.5)
celluloid-fsm (0.20.5)
celluloid-pool (0.20.5)
celluloid-supervision (0.20.6, 0.20.5)
CFPropertyList (3.0.0)
chandler (0.7.0)
childprocess (0.9.0, 0.8.0)
chosen-rails (1.8.7, 1.4.2)
chromedriver-helper (1.2.0, 1.1.0)
chronic (0.10.2)
chunky_png (1.3.4)
circleci (2.0.2, 0.1.1)
claide (1.0.2)
claide-plugins (0.9.2)
cocoapods (1.5.3, 1.2.1)
cocoapods-core (1.5.3, 1.2.1)
cocoapods-deintegrate (1.0.2, 1.0.1)
cocoapods-downloader (1.2.1, 1.1.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.3.0, 1.2.0)
cocoapods-try (1.1.0)
cocoon (1.2.11, 1.2.6)
codeclimate-test-reporter (1.0.8)
coderay (1.1.2, 1.1.1)
coercible (1.0.0)
coffee-rails (4.1.1, 4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.12.2, 1.9.1.1)
colored (1.2)
colored2 (3.1.2)
commander (4.4.3)
commander-fastlane (4.4.6)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
compass-rails (2.0.4)
concurrent-ruby (1.0.5)
connection_pool (2.2.2, 2.2.1)
cork (0.3.0)
countries (2.1.4, 2.0.1)
country_select (3.1.1, 3.0.0)
crack (0.4.3, 0.4.2)
crass (1.0.4, 1.0.3)
cucumber (3.1.2, 2.4.0)
cucumber-core (3.2.0, 1.5.0)
cucumber-expressions (6.0.1)
cucumber-rails (1.4.5, 1.4.3)
cucumber-tag_expressions (1.1.1)
cucumber-wire (0.0.1)
curb (0.9.6)
dalli (2.7.4)
danger (5.6.5, 5.5.11, 4.3.5)
danger-commit_lint (0.0.6, 0.0.5)
danger-gitlab (6.0.0)
danger-junit (0.7.4)
danger-plugin-api (1.0.0)
danger-simplecov_json (0.3.0)
database_cleaner (1.7.0, 1.6.2, 1.5.3, 1.4.1)
debug_inspector (0.0.3)
decent_exposure (3.0.2)
declarative (0.0.10)
declarative-option (0.1.0)
deep_cloneable (2.3.2, 2.1.1)
delayed_job (4.1.5, 4.1.4)
delayed_job_active_record (4.1.3, 4.1.2)
descendants_tracker (0.0.4)
devise (3.5.10)
did_you_mean (1.0.0)
diff-lcs (1.3, 1.2.5)
digest-crc (0.4.1)
docile (1.3.1, 1.1.5)
domain_name (0.5.20180417, 0.5.24)
dotenv (2.5.0)
draper (2.1.0)
easy_throttle_limit (0.1.0)
eh-keypay (0.1.77, 0.1.76, 0.1.75, 0.1.73, 0.1.70, 0.1.68, 0.1.65)
eh-myob (0.4.16, 0.4.15, 0.4.14, 0.4.12, 0.4.11)
eh_glutton_ratelimit (0.2.2)
eh_monitoring (0.2.4, 0.2.3, 0.2.2, 0.2.0)
eh_protobuf (1.2.29, 1.2.28, 1.2.23, 1.2.22, 1.2.21, 1.2.20, 1.2.18)
eh_xero (0.1.29, 0.1.28, 0.1.27)
ejs (1.1.1)
emoji_regex (0.1.1)
encryptor2 (1.0.0)
equalizer (0.0.11)
erubi (1.7.1)
erubis (2.7.0)
escape (0.0.4)
ethon (0.11.0)
excon (0.62.0, 0.45.3)
execjs (2.7.0)
executable-hooks (1.4.2)
fabrication (2.20.1, 2.13.2)
factory_bot (4.8.2)
factory_bot_rails (4.8.2)
factory_girl (4.9.0, 4.1.0)
factory_girl_rails (4.9.0, 4.1.0)
faker (1.9.1, 1.4.3)
fakeredis (0.6.0)
faraday (0.15.2, 0.14.0, 0.13.1, 0.9.2)
faraday-cookie_jar (0.0.6)
faraday-http-cache (1.3.1)
faraday_middleware (0.12.2, 0.10.0)
fast_stack (0.1.0)
fastimage (2.1.3)
fastlane (2.101.1, 2.99.0)
fastlane-plugin-badge (1.1.0)
fastlane-plugin-get_version_code (0.2.0)
fcm (0.0.2)
feature_flag_assistant (1.2.1, 1.2.0)
ffi (1.9.25, 1.9.18, 1.9.10, 1.9.8)
figaro (1.1.1)
filestack (2.4.0)
firebase (0.2.6)
flamegraph (0.9.5, 0.1.0)
formatador (0.2.5)
fourflusher (2.0.1)
fuzzy_match (2.0.4)
gem-wrappers (1.3.2)
get_process_mem (0.2.1)
gh_inspector (1.1.3)
gherkin (5.1.0, 4.0.0)
git (1.5.0, 1.4.0, 1.3.0)
github_api (0.16.0)
gitlab (4.4.0)
globalid (0.4.1, 0.3.7)
gon (6.2.1, 5.2.3)
google-api-client (0.21.2)
google-protobuf (3.6.1 universal-darwin, 3.6.0 universal-darwin, 3.5.1.2 universal-darwin)
google_drive (2.1.11)
googleapis-common-protos-types (1.0.2, 1.0.1)
googleauth (0.6.4, 0.6.2, 0.5.1)
grape (1.1.0, 0.13.0)
grape-route-helpers (2.1.0, 1.2.2)
grape_has_scope (0.2.0)
grpc (1.14.2 universal-darwin, 1.14.1 universal-darwin, 1.14.0 universal-darwin, 1.13.0 universal-darwin, 1.12.0 universal-darwin)
guard (2.14.2, 2.14.0)
guard-compat (1.2.1)
guard-rspec (4.7.3, 4.7.2)
guard-rubocop (1.3.0)
hamlit (2.8.10, 2.3.1)
hamlit-rails (0.2.0, 0.1.0)
has_scope (0.7.2, 0.6.0)
hashdiff (0.3.7)
hashery (2.1.2, 2.1.1)
hashie (3.5.7, 3.5.6)
hashie-forbidden_attributes (0.1.1)
heroics (0.0.24, 0.0.14)
highline (2.0.0, 1.7.10)
hike (1.2.3)
hitimes (1.3.0, 1.2.6, 1.2.3)
http-cookie (1.0.3, 1.0.2)
httparty (0.16.2, 0.15.6)
httpclient (2.8.3)
hutch (0.25.0, 0.23.1)
i18n (0.9.5, 0.9.1, 0.8.4, 0.8.1, 0.7.0)
i18n_data (0.8.0, 0.7.0)
ice_nine (0.11.2, 0.11.1)
idn-ruby (0.1.0)
inflection (1.0.0)
inherited_resources (1.9.0, 1.6.0)
instana (1.7.8)
io-console (default: 0.4.5)
io-like (0.3.0)
jaro_winkler (1.5.1 x86_64-darwin-17, 1.4.0)
jbuilder (2.7.0, 2.3.0)
jeweler (2.3.9)
jmespath (1.4.0, 1.0.2)
jquery-rails (4.0.4)
jquery-ui-rails (4.0.4)
json (2.1.0, 1.8.6, default: 1.8.3)
json_spec (1.1.5, 1.1.4)
jsonapi (0.1.1.beta6)
jsonapi-parser (0.1.1.beta3)
jsonapi-renderer (0.2.0, 0.1.1.beta1)
jwt (2.1.0, 1.5.6)
kaminari (1.1.1, 1.0.1, 0.16.3)
kaminari-actionview (1.1.1, 1.0.1)
kaminari-activerecord (1.1.1, 1.0.1)
kaminari-core (1.1.1, 1.0.1)
knapsack_pro (0.56.0, 0.43.0)
kramdown (1.17.0, 1.16.2, 1.15.0)
launchy (2.4.3)
letter_opener (1.6.0)
levenshtein-ffi (1.1.0)
listen (3.0.8, 3.0.7)
little-plugger (1.1.4)
logging (2.2.2)
logglier (0.2.13)
lograge (0.10.0, 0.4.1)
loofah (2.2.2, 2.1.1, 2.0.3)
lumberjack (1.0.13, 1.0.10)
macaddr (1.7.1)
mail (2.7.0, 2.6.6, 2.6.4)
memcachier (0.0.2)
memoist (0.16.0)
metaclass (0.0.4)
method_source (0.9.0, 0.8.2)
mime-types (3.2.2, 3.1, 2.99.3)
mime-types-data (3.2018.0812, 3.2016.0521)
mimemagic (0.3.2)
mini_magick (4.5.1, 3.7.0)
mini_mime (1.0.1, 1.0.0)
mini_portile2 (2.3.0, 2.1.0)
minitest (5.11.3, 5.11.1, 5.10.3, 5.10.2, 5.10.1, 5.8.5)
mixpanel-ruby (2.2.0, 1.6.0)
mocha (1.7.0, 1.1.0)
mocha-on-bacon (0.2.3, 0.2.2)
molinillo (0.6.5, 0.5.7)
moneta (0.8.1, 0.8.0)
monetize (1.7.0, 1.1.0)
money (6.11.3, 6.5.1)
money-rails (1.11.0, 1.4.1)
msgpack (1.2.4, 1.2.2)
multi_json (1.13.1, 1.12.2)
multi_test (0.1.2)
multi_xml (0.6.0)
multipart-post (2.0.0)
mustermann (1.0.3)
mustermann-grape (1.0.0)
myob-api (0.10.3)
nanaimo (0.2.6)
nap (1.1.0)
naturally (2.2.0)
nenv (0.3.0)
neovim (0.7.1)
net-sftp (2.1.2)
net-ssh (5.0.2, 2.9.2)
net-telnet (0.1.1)
netrc (0.11.0, 0.10.3, 0.7.8)
newrelic_rpm (5.3.0.346, 3.12.1.298)
nio4r (2.1.0, 2.0.0)
no_proxy_fix (0.1.2)
nokogiri (1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.7.1)
nokogumbo (1.5.0)
notiffany (0.1.1, 0.1.0)
oauth (0.4.7)
oauth2 (1.4.0)
octokit (4.11.0, 4.9.0, 4.8.0, 4.7.0)
oj (3.3.9)
omniauth (1.8.1, 1.7.1)
omniauth-myob (0.0.2)
omniauth-oauth2 (1.5.0, 1.4.0)
open4 (1.3.4)
optimist (3.0.0)
options (2.3.2)
orm_adapter (0.5.0)
os (1.0.0, 0.9.6)
ox (2.9.4)
paper_trail (4.0.2, 4.0.0.rc1)
parallel (1.12.1, 1.11.2, 1.10.0)
parallel_tests (2.22.1, 2.7.1)
parser (2.5.1.2, 2.5.1.0, 2.5.0.5, 2.4.0.2, 2.4.0.0)
pdf-core (0.7.0, 0.5.1)
pdf-reader (2.1.0, 1.3.3)
pg (1.1.2, 0.20.0, 0.18.4, 0.18.2)
phony (2.16.5, 2.15.42)
phony_rails (0.14.9, 0.14.5)
platform-api (2.1.0, 0.3.0)
plist (3.4.0)
polyamorous (1.2.0)
postageapp (1.3.1, 1.2.0)
power_assert (1.1.3, 1.1.2, 1.1.1, 0.2.6)
powerpack (0.1.2, 0.1.1)
prawn (2.2.2, 2.0.1)
prawn-fast-png (0.2.3)
prettybacon (0.0.2)
progress_bar (1.2.0, 0.3.1)
prometheus-client (0.8.0)
protected_attributes (1.1.4, 1.0.9)
pry (0.11.3, 0.10.3)
pry-byebug (3.6.0, 3.5.1, 3.5.0)
psych (3.0.2, default: 2.1.0)
public_suffix (3.0.3, 3.0.2, 2.0.5)
puma (3.12.0, 3.11.0, 3.7.1, 3.7.0, 3.4.0)
pundit (2.0.0, 1.1.0, 1.0.1)
pusher (1.3.1)
pusher-signature (0.1.8)
quantile (0.2.1)
quiet_assets (1.1.0)
rack (2.0.3, 2.0.1, 1.6.10)
rack-accept (0.4.5)
rack-attack (5.4.0)
rack-cache (1.8.0, 1.2)
rack-cors (1.0.2, 0.4.1, 0.4.0)
rack-mount (0.8.3)
rack-protection (2.0.3, 2.0.1, 2.0.0, 1.5.5, 1.5.3)
rack-test (0.6.3)
rack-timeout (0.5.1, 0.3.2)
rack_session_access (0.2.0, 0.1.1)
rails (5.0.6, 5.0.2, 4.2.9)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.3, 2.0.2, 1.0.9)
rails-html-sanitizer (1.0.4, 1.0.3)
rails-i18n (4.0.9)
rails-observers (0.1.5, 0.1.2)
rails_12factor (0.0.3)
rails_pattern_view (0.2.4)
rails_serve_static_assets (0.0.5, 0.0.4)
rails_stdout_logging (0.0.5, 0.0.3)
railties (5.0.6, 5.0.2, 4.2.9)
rainbow (3.0.0, 2.2.2, 2.2.1)
rake (12.3.1, 12.3.0, 12.0.0, 10.5.0, 10.4.2)
rake-compiler (0.9.5)
ransack (1.8.9, 1.6.6)
rb-fsevent (0.10.3, 0.10.2, 0.9.7, 0.9.5)
rb-inotify (0.9.10, 0.9.7, 0.9.5)
rbtrace (0.4.11, 0.4.7)
rdoc (6.0.4, default: 4.2.1)
recaptcha (4.12.0, 4.3.1)
redis (4.0.2, 4.0.1, 3.3.5, 3.3.3)
redis-actionpack (5.0.2)
redis-activesupport (5.0.7)
redis-namespace (1.6.0, 1.5.3)
redis-rack (2.0.4)
redis-rack-cache (2.0.2)
redis-rails (5.0.2)
redis-store (1.5.0)
remotipart (1.4.2, 1.2.1)
render_anywhere (0.0.12)
representable (3.0.4)
request_store (1.4.1, 1.1.0)
responders (2.4.0, 2.3.0)
rest-client (1.8.0)
restforce (3.0.1, 2.4.2)
retriable (3.1.2, 3.0.1, 2.1.0)
rmagick (2.16.0, 2.15.2)
rouge (2.0.7)
rspec (3.8.0, 3.7.0, 3.5.0, 3.4.0)
rspec-activemodel-mocks (1.0.3, 1.0.1)
rspec-collection_matchers (1.1.3, 1.1.2)
rspec-core (3.8.0, 3.7.1, 3.7.0, 3.5.4, 3.4.4)
rspec-expectations (3.8.1, 3.7.0, 3.5.0, 3.4.0)
rspec-instafail (1.0.0)
rspec-its (1.2.0)
rspec-mocks (3.8.0, 3.7.0, 3.5.0, 3.4.1)
rspec-rails (3.7.2, 3.5.2, 3.4.2)
rspec-support (3.8.0, 3.7.1, 3.7.0, 3.5.0, 3.4.1)
rspec_junit_formatter (0.4.1, 0.3.0, 0.2.3)
rspec_sequel_matchers (0.4.0)
rubocop (0.59.0, 0.57.0, 0.54.0, 0.53.0, 0.52.0, 0.49.1, 0.47.1)
rubocop-rspec (1.22.2)
ruby-kafka (0.7.0, 0.5.5, 0.5.1)
ruby-macho (1.2.0, 1.1.0)
ruby-progressbar (1.10.0, 1.9.0, 1.8.1)
ruby-rc4 (0.1.5)
rubygems-bundler (1.4.4)
rubyzip (1.2.2, 1.2.1)
rvm (1.11.3.9)
safe_yaml (1.0.4)
salesforce_bulk_api (0.0.12)
sanitize (4.6.6, 4.6.4)
sass (3.5.7, 3.4.14)
sass-listen (4.0.0)
sass-rails (5.0.7, 5.0.1)
sawyer (0.8.1)
scrub_rb (1.0.1)
security (0.1.3)
select2-rails (4.0.3, 3.5.9.1)
selenium-webdriver (3.4.4)
semver2 (3.4.2)
sentry-raven (2.7.4, 2.7.1, 2.4.0, 2.3.1)
sequel (4.45.0)
shellany (0.0.1)
shoulda-matchers (3.1.2, 2.8.0)
sidekiq (5.1.3, 5.0.5, 4.2.9)
sidekiq-limit_fetch (3.4.0)
signet (0.8.1)
simctl (1.6.5)
simple_form (4.0.0, 3.1.0)
simplecov (0.16.1, 0.13.0, 0.12.0, 0.10.0)
simplecov-html (0.10.2, 0.10.0)
sinatra (1.4.7)
sixarm_ruby_unaccent (1.2.0, 1.1.1)
slack-notifier (2.3.2)
slop (3.6.0)
sort_alphabetical (1.1.0)
spring (2.0.2, 1.7.2)
spring-commands-cucumber (1.0.1)
spring-commands-rspec (1.0.4)
sprockets (3.7.2, 3.7.1, 2.12.5)
sprockets-rails (3.2.1, 3.2.0, 2.3.3)
stackprof (0.2.12, 0.2.11)
steak (2.0.0)
subexec (0.2.3)
sys-proctable (1.1.5 universal-darwin)
systemu (2.6.5)
temple (0.8.0, 0.7.6)
terminal-notifier (1.8.0)
terminal-table (1.8.0)
test-queue (0.4.2)
test-unit (3.2.8, 3.1.5)
test_after_commit (1.1.0, 0.4.1)
test_retry (0.1.7)
thor (0.20.0, 0.19.4, 0.19.1)
thread_safe (0.3.6)
tilt (2.0.8, 2.0.5, 1.4.1)
timecop (0.9.1, 0.8.1, 0.7.4)
timers (4.1.2, 4.1.1)
tinymce-rails (4.8.2, 4.1.6)
trollop (2.1.2)
ttfunk (1.5.1, 1.4.0)
tty-cursor (0.6.0, 0.5.0)
tty-screen (0.6.5, 0.6.4)
tty-spinner (0.8.0)
twilio-ruby (5.10.2, 5.5.1, 5.5.0)
twitter-text (2.1.0, 1.14.7)
typhoeus (1.3.0)
tzinfo (1.2.5, 1.2.4, 1.2.3)
uber (0.1.0)
uglifier (4.1.18, 3.0.2)
unf (0.1.4)
unf_ext (0.0.7.5, 0.0.7.1)
unicode-display_width (1.4.0, 1.3.2, 1.3.0, 1.1.3)
unicode_utils (1.4.0)
uuid (2.3.9, 2.3.8)
vcr (4.0.0, 2.9.3)
versionist (1.7.0, 1.4.1)
virtus (1.0.5)
warden (1.2.7, 1.2.6)
webmock (3.4.2, 3.4.1, 2.3.2, 1.21.0)
websocket-driver (0.6.5)
websocket-extensions (0.1.3, 0.1.2)
wicked (1.3.3, 1.1.1)
wicked_pdf (1.1.0)
wisper (2.0.0, 1.6.0)
wkhtmltopdf-binary (0.12.4, 0.12.3.1)
word_wrap (1.0.0)
xcodeproj (1.5.9)
xcpretty (0.2.8)
xcpretty-travis-formatter (1.0.0)
xeroizer (2.16.5)
xml-simple (1.1.5)
xpath (2.1.0)
yard (0.9.16, 0.9.15, 0.9.12, 0.9.5)
zendesk_api (1.16.0, 1.14.0)
```

**Comment by gabifiolek** [comment]
@huyvohcmc Thank you, and please take a look on open issues in **bootsnap** repo:
https://github.com/Shopify/bootsnap/issues/137
https://github.com/Shopify/bootsnap/issues/180
It looks very similar to your case.

**Comment by huyvohcmc** [comment]
@gabifiolek I think I know what the problem is. Filestack has a dependency `progress_bar` and `progress_bar` has a dependency `options`, but somehow when running `bundle` it doesn't install gem `options`, which cause the error.
